### ISSUE TITLE
Update `use_gitlab_ci()` for R packages, coverage and pkgdown

### ISSUE THREAD

**Issue by statnmap** [ThinkR-open/gitlabr#21]
Todo

- [x] Check package + pkgdown + coverage
- [x] Check package with {renv}
- [x] Build bookdown
- [ ] Build bookdown with {renv}
- [x] Build bookdown with dev and production versions
- [x] Add Rbuildignore for "cache/", "ci/lib/" when running use_gitlab_ci()
- [x] Add system dependencies sections
- [ ] Add badges to Readme.Rmd
- [x] Add message (and command?) to retrieve coverage % on GitLab UI: `Coverage: \d+\.\d+`

See. https://gitlab.com/rdes_dreal/propre.rpls/-/blob/dev/.gitlab-ci.yml

**Comment by statnmap** [comment]
I think this would be interesting to create templates in "inst" with reduced version of the yaml below.  
This would probably be easier to maintain than the current implementation of `use_gitlab_ci()`.  

Last complete version with check, main/dev versions of {pkgdown} + coverage, and global package cache: 
```yaml
image: rocker/geospatial

variables:
  R_LIBS_USER: "ci/lib"

cache:
  key: global-cache
  paths:
      - ci/lib/

stages:
  - build
  - test
  - pkgdown
  - pkgdown-move
  - deploy

building:
  stage: build
  script:
    - mkdir -p $R_LIBS_USER
    - apt update -qq && apt install -y libharfbuzz-dev libfribidi-dev
    - Rscript -e '.libPaths(c(Sys.getenv("R_LIBS_USER"), .libPaths()));remotes::install_deps(dependencies = TRUE, lib = Sys.getenv("R_LIBS_USER"))'
    - Rscript -e '.libPaths(c(Sys.getenv("R_LIBS_USER"), .libPaths()));remotes::install_cran(c("pkgdown"), lib = Sys.getenv("R_LIBS_USER"))'
    - Rscript -e '.libPaths(c(Sys.getenv("R_LIBS_USER"), .libPaths()));devtools::check()'

# To have the coverage percentage appear as a gitlab badge follow these
# instructions:
# https://docs.gitlab.com/ee/user/project/pipelines/settings.html#test-coverage-parsing
# The coverage parsing string is
# Coverage: \d+\.\d+

coverage:
    stage: test
    allow_failure: true
    when: on_success
    only:
        - master
        - dev
    script:
        - Rscript -e '.libPaths(c(Sys.getenv("R_LIBS_USER"), .libPaths()));covr::gitlab(quiet = FALSE);'
    artifacts:
        paths:
            - public
        expire_in: 30 days

# To produce a code coverage report as a GitLab page see
# https://about.gitlab.com/2016/11/03/publish-code-coverage-report-with-gitlab-pages/

# Create pkgdown for dev and master
integration:
    stage: pkgdown
    allow_failure: true
    when: on_success
    only:
        - master
        - dev
    script:
        - Rscript -e '.libPaths(c(Sys.getenv("R_LIBS_USER"), .libPaths()));remotes::install_local();pkgdown::build_site()'
    artifacts:
        paths:
            - docs
        expire_in: 30 days

# Move pkgdown for dev but recover previous master version if it exists
integration-dev:
    stage: pkgdown-move
    dependencies:
        - integration
    only:
        - dev
    script:
        - mkdir -p public/dev
        - wget https://gitlab.com/rdes_dreal/propre.antidote/-/jobs/artifacts/master/download?job=pages &&
          unzip -o download?job=pages &&
          rm download?job=pages &&
          echo "copied master artifacts" ||
          echo "copied master artifacts failed"
        - cp -r docs/* public/dev
    artifacts:
        paths:
            - public
        expire_in: 30 days

# Move pkgdown for master but recover previous dev version if it exists
integration-master:
    stage: pkgdown-move
    dependencies:
        - integration
    only:
        - master
    script:
        - mkdir -p public
        - wget https://gitlab.com/rdes_dreal/propre.antidote/-/jobs/artifacts/dev/download?job=pages &&
          unzip -o download?job=pages &&
          rm download?job=pages &&
          echo "copied dev artifacts" ||
          echo "copied dev artifacts failed"
        - cp -r docs/* public
    artifacts:
        paths:
            - public
        expire_in: 30 days

# Deploy pkgdown
pages:
    stage: deploy
    script:
        - echo "deployment with cache ?"
    artifacts:
        paths:
            - public
    only:
        - master
        - dev
```

Explore the effect of not "expire" artifacts. I think that after 30 days without development the public page disappear, but if nothing expires, maybe the server uses too much space for artifacts.

**Comment by statnmap** [comment]
For private project, this may require an access TOKEN to download artifacts : https://gitlab.com/profile/personal_access_tokens

**Comment by MargotBr** [comment]
For library of packages management to avoid `.libPaths(c(Sys.getenv("R_LIBS_USER"), .libPaths()))` in `.gitlab-ci.yml ` files :

**Settings > CI/CD > Variables > R_LIBS = ci/lib**

![Capture d’écran 2021-04-06 à 14 38 38](https://user-images.githubusercontent.com/20540890/113711923-cca56280-96e5-11eb-82d9-4c468f499aa0.png)

```
image: rocker/verse

cache:
  key: global-cache
  paths:
      - $R_LIBS
    
stages:
  - build
  
building:
  stage: build
  script:
    - echo "Library path for packages :" $R_LIBS
    - mkdir -p $R_LIBS
    - Rscript -e 'install.packages(c("remotes"))'
    - Rscript -e 'remotes::install_deps(dependencies = TRUE, upgrade = "never")'
    - Rscript -e 'remotes::install_cran(c("here", "ggrepel", "thinkr", "rvg", "systemfonts", "gdtools", "officer", "uuid"), upgrade = "never")'
    - echo "Packages in library :" ls $R_LIBS
    - ls $R_LIBS
    - Rscript -e 'rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")'
```

Puis dans nada dans le .yml

**Comment by statnmap** [comment]
Maybe create a dedicated repository to store and download possible CI yml, like for github actions, so that you can have the latest yml, even without the latest {gitlabr} version

**Comment by statnmap** [comment]
Set variable inside the gitlab.ci
```
variables:
  GIT_DEPTH: 10
  REPO_NAME: "https://packagemanager.rstudio.com/all/__linux__/focal/latest"
  R_LIBS: "ci/lib"
```
