### ISSUE TITLE
feat: Centralize the script to deploy on Connect

### ISSUE THREAD

**Issue by MargotBr** [ThinkR-open/gitlabr#87]
## Validation

- [ ] `gitlabr::use_gitlab_ci(type = "check-coverage-pkgdown-connect")` generates the `gitlab-ci.yml` automatically, with a step to deploy on Connect - No manual modifications is needed
- [ ] A document explains how to create the environment variables needed

## Tech

_WIP_ 

- [ ] Add a new file `inst/gitlab-ci/dev_history_connect.R` with: 

````
# Bypassing the limitation of number of files 
# to push to Connect so that we can push large things
options(rsconnect.max.bundle.files = 1e5)

if (!requireNamespace("rsconnect", quietly = TRUE)) {
  install.packages("rsconnect")
}

if (!requireNamespace("cli", quietly = TRUE)) {
  install.packages("cli")
}

if (!requireNamespace("httr", quietly = TRUE)) {
  install.packages("httr")
}

connect_url <- httr::modify_url(base = url, path = "__api__")

cli::cat_rule("Building book")

withr::with_dir(
  "_book",
  {
    rsconnect::writeManifest()
  }
)

cli::cat_rule("Adding server")

rsconnect::addServer(
  connect_url,
  name = "connect"
)

cli::cat_rule("Adding user")
rsconnect::connectApiUser(
  account = Sys.getenv("CONNECT_USER"),
  server = "connect",
  apiKey = Sys.getenv("CONNECT_API_KEY")
)

appFiles <- list.files(
  "_book",
  recursive = TRUE
)

cli::cat_rule("Deploying")
rsconnect::deployApp(
  "_book",
  appName = Sys.getenv("APP_NAME"),
  appFiles = appFiles,
  appPrimaryDoc = "index.html",
  account = Sys.getenv("CONNECT_USER"),
  server = "connect",
  forceUpdate = FALSE
)
````

- [ ] Create a new function: `deploy_connect()` with:

````
wget("https://github.com/statnmap/gitlabr/tree/main/inst/gitlab-ci/dev_history_connect.R")
````

- [ ] In `inst/gitlab-ci/` add un `.yml` file specific to push to Connect with:

````
connect:
    stage: deploy-connect
    dependencies:
        - integration
    only:
        - master
        - main
    script:
        - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/jobs/artifacts/$CI_DEFAULT_BRANCH/download?job=pages" &&
              unzip artifacts.zip &&
              rm artifacts.zip &&
              echo "copied $CI_DEFAULT_BRANCH artifacts" ||
              echo "copied $CI_DEFAULT_BRANCH artifacts failed"'
        - Rscript "gitlabr::deploy_connect(app_name = Sys.getenv(APP_NAME))"
````
